<option value="Abnormal & Clinical Psychology, MSc" >Abnormal & Clinical Psychology, MSc (Taught Masters)</option>
<option value="Aerospace Engineering, MSc" >Aerospace Engineering, MSc (Taught Masters)</option>
<option value="Ageing Studies, MSc" >Ageing Studies, MSc (Taught Masters)</option>
<option value="Ancient Egyptian Culture, MA" >Ancient Egyptian Culture, MA (Taught Masters)</option>
<option value="Ancient History and Classical Culture, MA" >Ancient History and Classical Culture, MA (Taught Masters)</option>
<option value="Ancient Narrative Literature, MA" >Ancient Narrative Literature, MA (Taught Masters)</option>
<option value="Business Administration, MBA" >Business Administration, MBA (Taught Masters)</option>
<option value="Business Economics with Computing, MSc" >Business Economics with Computing, MSc (Taught Masters)</option>
<option value="Business Economics with Finance, MSc" >Business Economics with Finance, MSc (Taught Masters)</option>
<option value="Business Economics, MSc" >Business Economics, MSc (Taught Masters)</option>
<option value="Chemical Engineering, MSc" >Chemical Engineering, MSc (Taught Masters)</option>
<option value="Childhood Studies, MA" >Childhood Studies, MA (Taught Masters)</option>
<option value="Chronic Condition Management, MSc" >Chronic Condition Management, MSc (Taught Masters)</option>
<option value="Civil Engineering, MSc" >Civil Engineering, MSc (Taught Masters)</option>
<option value="Classics, MA" >Classics, MA (Taught Masters)</option>
<option value="Communication Systems, MSc" >Communication Systems, MSc (Taught Masters)</option>
<option value="Comparative Journalism, MA" >Comparative Journalism, MA (Taught Masters)</option>
<option value="Creative Writing, MA" >Creative Writing, MA (Taught Masters)</option>
<option value="Development and Human Rights, MA" >Development and Human Rights, MA (Taught Masters)</option>
<option value="Developmental and Therapeutic Play, MA" >Developmental and Therapeutic Play, MA (Taught Masters)</option>
<option value="Digital Media, MA" >Digital Media, MA (Taught Masters)</option>
<option value="Diversity of Contemporary Writing, MA" >Diversity of Contemporary Writing, MA (Taught Masters)</option>
<option value="Early Modern History, MA" >Early Modern History, MA (Taught Masters)</option>
<option value="Egyptology, MA" >Egyptology, MA (Taught Masters)</option>
<option value="English Language Studies, MA" >English Language Studies, MA (Taught Masters)</option>
<option value="Health Informatics, MSc:::1:::SHLS" >Health Informatics, MSc (Taught Masters)</option>
<option value="Hispanic Studies, MA:::1:::HSPC" >Hispanic Studies, MA (Taught Masters)</option>
<option value="History, MA" >History, MA (Taught Masters)</option>
<option value="Human Geography, MA" >Human Geography, MA (Taught Masters)</option>
<option value="International Commercial Law, LLM" >International Commercial Law, LLM (Taught Masters)</option>
<option value="International Maritime Law, LLM" >International Maritime Law, LLM (Taught Masters)</option>
<option value="International Relations, MA" >International Relations, MA (Taught Masters)</option>
<option value="International Security and Development, MA" >International Security and Development, MA (Taught Masters)</option>
<option value="International Trade Law, LLM" >International Trade Law, LLM (Taught Masters)</option>
<option value="LLM International Business Law" >LLM International Business Law (Taught Masters)</option>
<option value="Latin American Studies, MA" >Latin American Studies, MA (Taught Masters)</option>
<option value="Law and Globalisation, LLM" >Law and Globalisation, LLM (Taught Masters)</option>
<option value="Literary Translation (French), MA" >Literary Translation (French), MA (Taught Masters)</option>
<option value="Aerospace Engineering, BEng" >Aerospace Engineering, BEng (BENG)</option>
<option value="Aerospace Engineering, MEng" >Aerospace Engineering, MEng (MENG)</option>
<option value="American St & Soc History w Intercal yr, BA" >American St & Soc History w Intercal yr, BA (BA)</option>
<option value="American St and Politics w Intercal yr, BA" >American St and Politics w Intercal yr, BA (BA)</option>
<option value="American Studies and Geography, BA" >American Studies and Geography, BA (BA)</option>
<option value="American Studies and Politics, BA" >American Studies and Politics, BA (BA)</option>
<option value="American Studies and Social History, BA" >American Studies and Social History, BA (BA)</option>
<option value="American Studs & Geography w Intercal yr, BA" >American Studs & Geography w Intercal yr, BA (BA)</option>
<option value="Applied Mathematics, BSc" >Applied Mathematics, BSc (BSC)</option>
<option value="BA American Studies (3 yrs)" >BA American Studies (3 yrs) (BA)</option>
<option value="BA American Studies and English:" >BA American Studies and English (BA)</option>
<option value="BA American Studies and French" >BA American Studies and French (BA)</option>
<option value="BA American Studies and German" >BA American Studies and German (BA)</option>
<option value="BA American Studies and History" >BA American Studies and History (BA)</option>
<option value="BA American Studies and Italian" >BA American Studies and Italian (BA)</option>
<option value="BA American Studies and Spanish" >BA American Studies and Spanish (BA)</option>
<option value="BA American Studies and Welsh" >BA American Studies and Welsh (BA)</option>
<option value="BA Egyptology & Ancient History" >BA Egyptology & Ancient History (BA)</option>
<option value="BA Egyptology & Classical Civilisation" >BA Egyptology & Classical Civilisation (BA)</option>
<option value="BA English & History (yr abroad)" >BA English & History (yr abroad) (BA)</option>
<option value="BA English Literature" >BA English Literature (BA)</option>
<option value="French BA" >BA French (BA)</option>
<option value="BA German (with Legal Studies)" >BA German (with Legal Studies) (BA)</option>
<option value="BA Greek and Language Studies" >BA Greek and Language Studies (BA)</option>
<option value="BA History" >BA History (BA)</option>
<option value="BA Italian (with Business Studies)" >BA Italian (with Business Studies) (BA)</option>
<option value="BA Italian (with Computer Studies)" >BA Italian (with Computer Studies) (BA)</option>
<option value="BA Language Studies and Latin" >BA Language Studies and Latin (BA)</option>
<option value="BA Language Studies and Spanish" >BA Language Studies and Spanish (BA)</option>
<option value="BA Language Studies and Spanish (with Bus St):::1:::ZAPLSHSPC" >BA Language Studies and Spanish (with Bus St) (BA)</option>
<option value="BA Latin and Welsh" >BA Latin and Welsh (BA)</option>
<option value="BA Media Studies and French" >BA Media Studies and French (BA)</option>
<option value="BA Media Studies and Italian" >BA Media Studies and Italian (BA)</option>
<option value="BA Medieval Studies and Welsh" >BA Medieval Studies and Welsh (BA)</option>
<option value="BA Screen Studies" >BA Screen Studies (BA)</option>
<option value="BA Screen Studies & French" >BA Screen Studies & French (BA)</option>
<option value="BA Screen Studies & Italian" >BA Screen Studies & Italian (BA)</option>
<option value="BA Spanish" >BA Spanish (BA)</option>
<option value="BA Welsh (with Business Studies)" >BA Welsh (with Business Studies) (BA)</option>
<option value="BA Welsh (with Legal Studies)" >BA Welsh (with Legal Studies) (BA)</option>
<option value="BSC Biochemistry and Genetics" >Biochemistry and Genetics (BSC)</option>
<option value="Business Economics, BSc" >Business Economics, BSc (BSC)</option>
<option value="Business Management (Accounting), BSc" >Business Management (Accounting), BSc (BSC)</option>
<option value="Chemical & Biochemical Engineering, Ind MEng" >Chemical & Biochemical Engineering, Ind MEng (MENG)</option>
<option value="Chemical & Biochemical Engineering, MEng" >Chemical & Biochemical Engineering, MEng (MENG)</option>
<option value="Chemical Engineering, Graduate Diploma:::1:::CENG" >Chemical Engineering, Graduate Diploma (DIP CHEM ENG)</option>
<option value="Computer Science (Integrated), BSc" >Computer Science (Integrated), BSc (BSC)</option>
<option value="Computer Science (with French), BSc" >Computer Science (with French), BSc (BSC)</option>
<option value="Computer Science (with German), BSc" >Computer Science (with German), BSc (BSC)</option>
<option value="Computer Science (with Italian), BSc" >Computer Science (with Italian), BSc (BSC)</option>
<option value="Computer Science (with Spanish), BSc" >Computer Science (with Spanish), BSc (BSC)</option>
<option value="Materials Science and Engineering, MEng" >Materials Science and Engineering, MEng (MENG)</option>
<option value="Mathematics (with French), BSc" >Mathematics (with French), BSc (BSC)</option>
<option value="Mathematics (with German), BSc" >Mathematics (with German), BSc (BSC)</option>
<option value="Mathematics (with Spanish), BSc" >Mathematics (with Spanish), BSc (BSC)</option>
<option value="Mathematics (with Welsh), BSc" >Mathematics (with Welsh), BSc (BSC)</option>
<option value="Mathematics and Geo-Informatics, BSc" >Mathematics and Geo-Informatics, BSc (BSC)</option>
<option value="Mathematics and Physics, BSc" >Mathematics and Physics, BSc (BSC)</option>
<option value="Mathematics for Computer Science, BSc" >Mathematics for Computer Science, BSc (BSC)</option>
<option value="Mathematics for Finance, BSc" >Mathematics for Finance, BSc (BSC)</option>
<option value="Mathematics for ICT, BSc" >Mathematics for ICT, BSc (BSC)</option>
<option value="Mathematics, BSc" >Mathematics, BSc (BSC)</option>
<option value="Mathematics, MMath" >Mathematics, MMath (MMATH)</option>
<option value="Maths with Sports Science, BSc" >Maths with Sports Science, BSc (BSC)</option>
<option value="Mechanical Engineering, BEng" >Mechanical Engineering, BEng (BENG)</option>
<option value="Medical Biochemistry, BSc" >Medical Biochemistry, BSc (BSC)</option>
<option value="Medical Engineering (Integrated), BEng" >Medical Engineering (Integrated), BEng (BENG)</option>
<option value="Medical Engineering, BEng" >Medical Engineering, BEng (BENG)</option>
<option value="Medical Engineering, MEng" >Medical Engineering, MEng (MENG)</option>
<option value="Medical Genetics, BSc" >Medical Genetics, BSc (BSC)</option>
<option value="Medical Sciences and Humanities, BSc" >Medical Sciences and Humanities, BSc (BSC)</option>
<option value="Product Design Engineering, BEng" >Product Design Engineering, BEng (BENG)</option>
<option value="Product Design Engineering, MEng" >Product Design Engineering, MEng (MENG)</option>
<option value="Product Design Technology, BEng" >Product Design Technology, BEng (BENG)</option>
<option value="Psychology and Law, BSc" >Psychology and Law, BSc (BSC)</option>
<option value="Psychology and Spanish, BA" >Psychology and Spanish, BA (BA)</option>
<option value="Psychology and Welsh, BA" >Psychology and Welsh, BA (BA)</option>
<option value="Psychology, BSc" >Psychology, BSc (BSC)</option>
<option value="Public and Media Relations, BA" >Public and Media Relations, BA (BA)</option>
<option value="Pure Mathematics, BSc" >Pure Mathematics, BSc (BSC)</option>
<option value="Theoretical Physics, M Phys" >Theoretical Physics, M Phys (MPHYS)</option>
<option value="Translation Studies, BA" >Translation Studies, BA (BA)</option>
<option value="War and Society, BA" >War and Society, BA ()</option>
<option value="Welsh (with Computer Studies), BA" >Welsh (with Computer Studies), BA (BA)</option>
